# Make sure that the additional_dependencies here match pyproject.toml

ci:
  autofix_prs: false
  autoupdate_schedule: "monthly"

repos:
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.6
    hooks:
      - id: docformatter
        args: [ --in-place, --recursive ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format